version: '2'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: A4EvkEnXM97TlDOqxaGXx3ojoAOJg9H0
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:6-alpine
    container_name: redis
    volumes:
      - ./data/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
